### ISSUE TITLE
Ridiculous Size of Game

### ISSUE THREAD

**Issue by MatthewWid** [nugyflex/sifigame#1]
For a game that is so simple right now, is it really necessary for it to contain 1441 files and be over 500mb? It takes a ridiculously long time to sync for the first time.

Just use the files you need and use and don't include every single asset that you've made.

**Comment by nugyflex** [comment]
Yeah I accidently put a huge lens flare pack on there, its massive and I will delete it when I get home, the game itself I only 10mb

EDIT: Removed Signature

**Comment by nugycal** [comment]
Issue has been Resolved
